onlyBuiltDependencies:
    - '@prisma/client'
    - '@prisma/engines'
    - '@tailwindcss/oxide'
    - prisma
    - sharp
    - unrs-resolver
peerDependencyRules:
    allowAny:
        - '@hono/zod-validator'
        - 'zod'
        - 'zod-openapi'
